kubecostModel:
  containerStatsEnabled: true
  cloudCost:
    enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled is true to reduce cluster resources consumption. Set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)
prometheus:
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
