extraScrapeConfigs: |
  - job_name: kubecost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - kubecost-cost-analyzer.kubecost
      type: 'A'
      port: 9003
  - job_name: kubecost-networking
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
    # Scrape only the the targets matching the following metadata
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex:  kubecost-network-costs