apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubecost-metric-check
  name: kubecost-metric-check
spec:
  containers:
  - image: gcr.io/guestbook-227502/metric-check:1.0.0
    name: kubecost-metric-check
    env:
    - name: KUBECOST_SERVICE
      value: http://kubecost-cost-analyzer:9003/prometheusQuery
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never