apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubecost-metric-check
  name: kubecost-metric-check
spec:
  containers:
  - image: gcr.io/guestbook-227502/metric-check:1.0.0
    name: kubecost-metric-check
    imagePullPolicy: Always
    env:
    # Kubecost exposes the prometheusQuery endpoint at http://KUBECOST_SERVICE.YOUR_NAMESPACE:9003/prometheusQuery. The default service name is "kubecost-cost-analyzer.kubecost"
    - name: KUBECOST_SERVICE
      value: "http://kubecost-cost-analyzer.kubecost:9003/prometheusQuery"
    # if Kubecost is using a multi-cluster Prometheus, you must specify the label used to identify the cluster and cluster name
    # unless kubecostModel.promClusterIDLabel is set, the default is "cluster_id"
    - name: MULTI_CLUSTER
      value: "true"
    - name: PROM_CLUSTERID_LABEL
      value: "cluster_id"
    - name: CLUSTER_NAME
      value: "my-cluster-name"
    - name: OUTPUT_LABELS
      value: "false"
    - name: CHECK_LABELS
      value: "false"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never