apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubecost-networking
  labels:
    app.kubernetes.io/name: kubecost-network-costs
    app.kubernetes.io/instance: kubecost
    app: kubecost-network-costs
spec:
  endpoints:
    - port: metrics
      honorLabels: true
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - kubecost
  selector:
    matchLabels:
      app: kubecost-network-costs
      app.kubernetes.io/instance: kubecost
      app.kubernetes.io/name: cost-analyzer