apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubecost-networking
  labels:
    app.kubernetes.io/name: kubecost-network-costs
    app.kubernetes.io/instance: kubecost
    app: kubecost-network-costs
spec:
  podMetricsEndpoints:
    - port: metrics
      honorLabels: true
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: network-costs