---
# Source: https://github.com/kubecost/cost-analyzer-helm-chart/cost-analyzer/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-1.17.2
    heritage: Helm
    release: kubecost
  name: kubecost-grafana
