---
# Source: https://github.com/kubecost/cost-analyzer-helm-chart/cost-analyzer/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubecost-grafana-clusterrolebinding
  labels:
    app: grafana
    chart: grafana-1.17.2
    release: kubecost
    heritage: Helm
subjects:
  - kind: ServiceAccount
    name: kubecost-grafana
    namespace: kubecost
roleRef:
  kind: ClusterRole
  name: kubecost-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
