{
 "title": "Kubecost Network Transfer Data",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_id)" } },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Internet Transfer Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(kubecost_pod_network_egress_bytes_total{internet=\"true\", namespace=~\"$Namespace\", cluster_id=~\"$cluster\"}[60m])) / 1024 / 1024",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Cross Region Transfer Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(kubecost_pod_network_egress_bytes_total{internet=\"false\", sameRegion=\"true\", namespace=~\"$Namespace\", cluster_id=~\"$cluster\"}[60m])) / 1024 / 1024",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Cross Zone Transfer Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(kubecost_pod_network_egress_bytes_total{internet=\"false\", sameRegion=\"true\", namespace=~\"$Namespace\", cluster_id=~\"$cluster\", sameZone=\"false\"}[60m])) / 1024 / 1024",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  }
 ]
}