global:
  grafana:
    enabled: true # If false, Grafana will not be installed
    domainName: grafana.grafana #example grafana domain Ignored if enabled: true
    scheme: "http" # http or https, for the domain name above.
    proxy: true