kubecostProductConfigs:
  # cloudIntegrationSecret: cloud-integration
kubecostModel:
  containerStatsEnabled: true
  cloudCost:
    enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled=true
  federatedStorageConfigSecret: kubecost-object-store
serviceAccount: # this example uses AWS IRSA, which creates a service account with rights to the s3 bucket. If using keys+secrets in the federated-store, set create: true
  create: false
  name: kubecost-irsa-s3
kubecostDeployment:
  queryServiceReplicas: 1 # to improve performance, increase replica count. see: https://docs.kubecost.com/install-and-configure/install/etl-backup/query-service-replicas
global:
  prometheus:
    enabled: true
    # fqdn: http://prometheus-operated.monitoring:9090
  grafana: # prometheus metrics will be local cluster only, disable grafana to save resources
    enabled: false
    proxy: false
prometheus:
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
  nodeExporter:
    enabled: false