apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: aws-adot
    component: adot-collector-conf
  name: adot-collector-conf
data:
  adot-collector-config: |
    receivers:
      prometheus:
        config:
          global:
            external_labels:
              cluster: YOUR_CLUSTER_NAME_HERE
            scrape_interval: 60s
            scrape_timeout: 50s
          scrape_configs:
          - job_name: kubecost-agent
            honor_labels: true
            dns_sd_configs:
            - names:
              - kubecost-agent-metrics.kubecost-agent
              type: 'A'
              port: 9005
          # optionally add kubecost network costs scrape job:
          - job_name: kubecost-networking
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
            # Scrape only the the targets matching the following metadata
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
                action: keep
                regex:  kubecost
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                action: keep
                regex:  network-costs

          - job_name: 'kubernetes-service-endpoints'

            kubernetes_sd_configs:
            - role: endpoints

            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

            relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_scrape]
              action: keep
              regex: true

    exporters:
      prometheusremotewrite:
        # replace this with your endpoint
        endpoint: "https://aps-workspaces.YOUR_REGION.amazonaws.com/workspaces/ws-YOUR_WORKSPACE/api/v1/remote_write"
        auth:
          authenticator: sigv4auth
        namespace: "adot"
      logging:
        loglevel: debug

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
      # replace this with your region
      sigv4auth:
        region: "YOUR_REGION"

    service:
      extensions: [pprof, zpages, health_check, sigv4auth]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [logging, prometheusremotewrite]