federatedETL:
  agentOnly: true
  federatedCluster: true
  
kubecostProductConfigs:
  # clustername should be unique for all clusters
  clusterName: kubecostProductConfigs_clusterName
  # awsSpotDataRegion: AWS_kubecostProductConfigs_awsSpotDataRegion
  # awsSpotDataBucket: AWS_kubecostProductConfigs_awsSpotDataBucket
  # awsSpotDataPrefix: dev

kubecostModel:
  federatedStorageConfigSecret: federated-store

prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
    retention: 3d
    
networkCosts:
  enabled: true
  config:
    services:
      amazon-web-services: true
      # google-cloud-services: true
      # azure-cloud-services: true
