global:
  clusterId: cluster-one # cluster_id should be unique for all clusters
  existingSecret: federated-storage-secret
finopsagent:
  enabled: true
  agent:
    kubecost:
      projectID: "AWS_ACCOUNT_NUMBER"
      awsSpotDataBucket: "AWS_SPOT_DATA_BUCKET"
      awsSpotDataPrefix: "AWS_SPOT_DATA_PREFIX"
      awsSpotDataRegion: "AWS_SPOT_DATA_REGION"