cloudCost:
  enabled: true
  cloudIntegrationSecret: cloud-integration
  serviceAccount:
    create: false
    name: kubecost-serviceaccount-cur-athena
    useSharedServiceAccount: false
finopsagent:
  enabled: false
global:
  clusterId: cluster-one # cluster_id should be unique for all clusters
  existingSecret: federated-storage-secret
