kubecostProductConfigs:
  projectID: "AWS_kubecostProductConfigs_projectID"
  cloudIntegrationSecret: cloud-integration
  clusterName: AWS_kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  awsSpotDataRegion: AWS_kubecostProductConfigs_awsSpotDataRegion
  awsSpotDataBucket: AWS_kubecostProductConfigs_awsSpotDataBucket
  # awsSpotDataPrefix: dev
  serviceKeySecretName: aws-service-key # Used for Spot Data Feed and Unattached Disks/IP Addresses
prometheus:
  server:
    global:
      external_labels:
        cluster_id: kubecostProductConfigs_clusterName
networkCosts:
  enabled: true