apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    chart: cost-analyzer
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 1.96.0
    helm:
      releaseName: kubecost
      valueFiles:
        # Thanos is used both to ship the local cluster metrics via a prometheus sidecar and to query the global kubecost metrics store for all clusters
        - https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/values-thanos.yaml
        - https://raw.githubusercontent.com/kubecost/poc-common-configurations/main/argocd/kubecost-cluster-settings.yaml
      values: |
        kubecostProductConfigs:
          clusterName: myClusterName
        prometheus:
          server:
            global:
              external_labels:
                cluster_id: myClusterName
          # Disable node exporter+service account if cluster/node rightsizing recommendations are not required
          # In addition, node-export must be disabled if there is an existing daemonset: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus#disable-node-exporter-and-kube-state-metrics-recommended
          # nodeExporter:
          #   enabled: true
          # serviceAccounts:
          #   nodeExporter:
          #     create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true