apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    chart: cost-analyzer
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 1.96.0
    helm:
      releaseName: kubecost
      valueFiles:
        - "https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/values-thanos.yaml"
        - "https://raw.githubusercontent.com/kubecost/poc-common-configurations/main/argocd/kubecost-primary-cluster-settings.yaml"
      values: |
        kubecostProductConfigs:
          # clustername should be unique for all clusters
          clusterName: myClusterName
          # productKey:
          #   secretname: productkey
          #   enabled: false #not needed for eval
          # cloudIntegrationSecret: cloud-integration # only runs on primary cluster
        prometheus:
          server:
            global:
              external_labels:
                # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
                cluster_id: myClusterName
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true