kubecostModel:
  etlCloudAsset: true # set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)
prometheus:
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
networkCosts:
  enabled: true
  config:
    services:
      # set the provider that this cluster is on to true
      amazon-web-services: false
      google-cloud-services: false
      azure-cloud-services: false
