apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: kubecost-ingress-sub-path
spec:
  host: kubecost.your.com
  upstreams:
  - name: kubecost
    service: kubecost-cost-analyzer
    port: 9090
  routes:
  - path: ~ /kubecost/?(.*)
    action:
      proxy:
        upstream: kubecost
        rewritePath: /$1