kubecostProductConfigs:
  clusterName: dev_clusters
  productKey:
    secretname: productkey
    enabled: true
kubecostModel:
  warmCache: false
  warmSavingsCache: false
  etl: false
global:
  grafana:
    enabled: false
    proxy: false
  alertmanager:
    enabled: false