kubecostProductConfigs:
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  cloudIntegrationSecret: cloud-integration # only runs on primary cluster
prometheus:
  server:
    global:
      external_labels:
        cluster_id: kubecostProductConfigs_clusterName
networkCosts:
  enabled: true