kubecostProductConfigs:
  # clustername should be unique for all clusters, must set this line and cluster_id below
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   key: YOUR_KEY
  #   enabled: true # product key is not needed for eval

federatedETL:
  federatedCluster: true
  agentOnly: true

kubecostModel:
  federatedStorageConfigSecret: kubecost-federated-store
  
global:
  grafana:
    enabled: false
    proxy: false
    
prometheus:
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: kubecostProductConfigs_clusterName
    retention: 2d
  # Disable node exporter+service account if cluster/node rightsizing recommendations are not required
  # In addition, node-export must be disabled if there is an existing daemonset: https://guide.kubecost.com/hc/en-us/articles/4407601830679-Troubleshoot-Install#a-name-node-exporter-a-issue-failedscheduling-kubecost-prometheus-node-exporter
  # nodeExporter:
  #   enabled: false
  # serviceAccounts:
  #   nodeExporter:
  #     create: false
  
networkCosts:
  enabled: true
  config:
    services:
      # amazon-web-services: true
      google-cloud-services: true
      # azure-cloud-services: true
