kubecostProductConfigs:
  clusterName: kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false # product key is not needed for eval
kubecostModel:
  warmCache: false
  warmSavingsCache: false
  etl: false
  maxQueryConcurrency: 1
global:
  grafana:
    enabled: false
    proxy: false
  alertmanager:
    enabled: false
prometheus:
  server:
    global:
      external_labels:
        cluster_id: kubecostProductConfigs_clusterName
    retention: 2d
  nodeExporter:
    enabled: false
thanos:
  compact:
    enabled: false
  bucket:
    enabled: false
  query:
    enabled: false
  queryFrontend:
    enabled: false
networkCosts:
  enabled: true