kubecostProductConfigs:
  clusterName: kubecostProductConfigs_clusterName
  productKey:
    secretname: productkey
    enabled: false #not needed for eval
prometheus:
  server:
    global:
      external_labels:
        cluster_id: kubecostProductConfigs_clusterName
kubecostModel:
  warmCache: false
  warmSavingsCache: false
  etl: false
global:
  grafana:
    enabled: false
    proxy: false
  alertmanager:
    enabled: false
networkCosts:
  enabled: true