kubecostModel:
  warmCache: false
  warmSavingsCache: false
  etl: false
  etlCloudAsset: false
  maxQueryConcurrency: 1
global:
  grafana:
    enabled: false
    proxy: false
  prometheus:
    fqdn: http://<prometheus-server-service-name>.<prometheus-server-namespace>.svc:port
prometheus:
  enabled: false
networkCosts:
  enabled: true
  config:
    services:
      amazon-web-services: true
      google-cloud-services: true
      azure-cloud-services: true